------------------------------------------------------------
-- Demo 4 - Vector Embeddings with SQL Server 2025 and Ollama
-- This demo showcases SQL Server 2025's AI capabilities to generate and store
-- vector embeddings for StackOverflow posts using Ollama models
------------------------------------------------------------

------------------------------------------------------------
-- Step 1: Create a dedicated filegroup for embeddings storage
------------------------------------------------------------

/*
    Switch to the StackOverflow database to prepare for embeddings storage.
*/
USE [StackOverflow_Embeddings_Small];
GO

/*
    Create a dedicated filegroup for storing embeddings.
    This improves performance and organization by separating embeddings from other data.
*/
ALTER DATABASE [StackOverflow_Embeddings_Small]
ADD FILEGROUP EmbeddingsFileGroup;
GO

/*
    Add a new data file to the embeddings filegroup.
    Starting with 20GB and auto-growing in 64MB increments.
*/
ALTER DATABASE [StackOverflow_Embeddings_Small]
ADD FILE (
    NAME = N'StackOverflowEmbeddings',
    FILENAME = N'/var/opt/mssql/data/StackOverflow_Embeddings.ndf',
    SIZE = 20GB,
    FILEGROWTH = 64MB
) TO FILEGROUP EmbeddingsFileGroup;
GO

------------------------------------------------------------
-- Step 2: Create the PostEmbeddings table
------------------------------------------------------------

/*
    Create a table to store vector embeddings for StackOverflow posts.
    The Embedding column uses VECTOR(768) to store 768-dimensional embeddings
    generated by the nomic-embed-text model.
    The table is stored on the dedicated EmbeddingsFileGroup for optimal performance.
*/
CREATE TABLE dbo.PostEmbeddings (
    PostID INT NOT NULL PRIMARY KEY CLUSTERED, -- FK to Posts table
    Embedding VECTOR(768) NOT NULL,            -- Vector embedding (from Ollama)
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME NULL
) ON EmbeddingsFileGroup;
GO

------------------------------------------------------------
-- Step 3: Enable external REST endpoint invocation
------------------------------------------------------------

/*
    Switch to the embeddings database for external model configuration.
*/
PRINT 'Step 2: Creating external model connection to load-balanced Ollama...';
GO

/*
    Enable external REST endpoint invocation in SQL Server.
    This allows SQL Server to communicate with external AI services like Ollama.
*/
PRINT 'Enabling external REST endpoint invocation...'
GO
sp_configure 'external rest endpoint enabled', 1
GO
RECONFIGURE WITH OVERRIDE;
GO

------------------------------------------------------------
-- Step 4: Create external models for Ollama endpoints
------------------------------------------------------------

/*
    Create an external model pointing to the load-balanced nginx endpoint (port 443).
    This endpoint distributes requests across multiple Ollama instances for better performance.
*/
CREATE EXTERNAL MODEL ollama_lb
WITH (
    LOCATION = 'https://host.docker.internal:443/api/embed',
    API_FORMAT = 'Ollama',
    MODEL_TYPE = EMBEDDINGS,
    MODEL = 'nomic-embed-text'
);
GO

/*
    Create an external model pointing to a single Ollama backend (port 444).
    This endpoint routes to a single Ollama instance for comparison/testing purposes.
*/
CREATE EXTERNAL MODEL ollama_single
WITH (
    LOCATION = 'https://host.docker.internal:444/api/embed',
    API_FORMAT = 'Ollama',
    MODEL_TYPE = EMBEDDINGS,
    MODEL = 'nomic-embed-text'
);
GO

------------------------------------------------------------
-- Step 5: Test the external model connections
------------------------------------------------------------

/*
    Test the load-balanced Ollama connection by generating a test embedding.
    This verifies that SQL Server can communicate with the Ollama service.
*/
PRINT 'Testing load-balanced Ollama connection...';
GO

BEGIN TRY
    DECLARE @test_result NVARCHAR(MAX);
    DECLARE @test_vector VECTOR(768);
    
    SET @test_vector = AI_GENERATE_EMBEDDINGS(N'test message for load balancer' USE MODEL ollama_lb);
    SET @test_result = CONVERT(NVARCHAR(MAX), @test_vector);
    
    PRINT 'Load-balanced connection successful!';
    PRINT 'Sample embedding (first 100 chars): ' + LEFT(@test_result, 100);
END TRY
BEGIN CATCH
    PRINT 'Error testing load-balanced connection:';
    PRINT ERROR_MESSAGE();
END CATCH;
GO

/*
    Test the single backend Ollama connection.
*/
PRINT 'Testing single backend Ollama connection...';
GO

BEGIN TRY
    DECLARE @test_result NVARCHAR(MAX);
    DECLARE @test_vector VECTOR(768);
    
    SET @test_vector = AI_GENERATE_EMBEDDINGS(N'test message for single backend' USE MODEL ollama_single);
    SET @test_result = CONVERT(NVARCHAR(MAX), @test_vector);
    
    PRINT 'Single backend connection successful!';
    PRINT 'Sample embedding (first 100 chars): ' + LEFT(@test_result, 100);
END TRY
BEGIN CATCH
    PRINT 'Error testing single backend connection:';
    PRINT ERROR_MESSAGE();
END CATCH;
GO

------------------------------------------------------------
-- Step 6: Generate embeddings for StackOverflow posts
------------------------------------------------------------

/*
    Generate vector embeddings for post titles in batches.
    This processes posts that don't yet have embeddings stored.
    Using the load-balanced endpoint for better performance.
*/
PRINT 'Generating embeddings for StackOverflow posts...';
GO

DECLARE @BatchSize INT = 1000;
DECLARE @ProcessedCount INT = 0;

WHILE EXISTS (
    SELECT 1 
    FROM dbo.Posts p
    WHERE p.Title IS NOT NULL
        AND p.Id NOT IN (SELECT PostID FROM dbo.PostEmbeddings)
)
BEGIN
    INSERT INTO dbo.PostEmbeddings (PostID, Embedding, CreatedAt)
    SELECT TOP (@BatchSize)
        p.Id,
        AI_GENERATE_EMBEDDINGS(p.Title USE MODEL ollama_lb) AS Embedding,
        GETDATE() AS CreatedAt
    FROM 
        dbo.Posts p
    WHERE 
        p.Title IS NOT NULL
        AND p.Id NOT IN (SELECT PostID FROM dbo.PostEmbeddings);
    
    SET @ProcessedCount = @ProcessedCount + @@ROWCOUNT;
    PRINT 'Processed ' + CAST(@ProcessedCount AS VARCHAR(10)) + ' posts';
    
    -- Brief pause between batches to avoid overwhelming the system
    WAITFOR DELAY '00:00:01';
END;
GO

------------------------------------------------------------
-- Step 7: Verify embeddings were created
------------------------------------------------------------

/*
    Check the PostEmbeddings table to verify embeddings were generated.
    Display the first 10 embeddings with their metadata.
*/
SELECT TOP 10 
    pe.PostID,
    p.Title,
    pe.Embedding,
    pe.CreatedAt
FROM 
    dbo.PostEmbeddings pe
INNER JOIN 
    dbo.Posts p ON pe.PostID = p.Id
ORDER BY 
    pe.PostID;
GO

------------------------------------------------------------
-- Cleanup (commented out for safety)
------------------------------------------------------------

/*
    Drop external models if needed.
    Uncomment to remove Ollama endpoint registrations.
*/
-- DROP EXTERNAL MODEL ollama_lb;
-- GO
-- DROP EXTERNAL MODEL ollama_single;
-- GO

/*
    Drop the PostEmbeddings table if needed.
    Uncomment to remove all stored embeddings.
*/
-- DROP TABLE dbo.PostEmbeddings;
-- GO